#############################################################################
# Generated by PAGE version 5.3
#  in conjunction with Tcl version 8.6
#  Jul 27, 2020 10:45:48 AM IST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 600x450+377+148
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra44 \
        -borderwidth 2 -relief groove -background #ff8080 -height 445 \
        -width 595 
    vTcl:DefineAlias "$top.fra44" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra44
    label $site_3_0.lab45 \
        -background #ff8080 -disabledforeground #a3a3a3 \
        -font {-family @Meiryo -size 18 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #f5010a -text {!!!Let's play Rock,Paper,Scissor!!!} 
    vTcl:DefineAlias "$site_3_0.lab45" "Label1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #008000 -disabledforeground #a3a3a3 \
        -font {-family Century -size 12 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Start 
    vTcl:DefineAlias "$site_3_0.but46" "Button1" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_3_0.lis47 \
        -background #ff8040 -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -height 122 -width 424 
    $site_3_0.lis47 configure -font "TkFixedFont"
    $site_3_0.lis47 insert end text
    vTcl:DefineAlias "$site_3_0.lis47" "Listbox1" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex48 \
        -background #80ff80 -font TkTextFont -foreground black -height 44 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 144 -wrap word 
    $site_3_0.tex48 configure -font "TkTextFont"
    $site_3_0.tex48 insert end text
    vTcl:DefineAlias "$site_3_0.tex48" "Text1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab49 \
        -background #ff8080 -disabledforeground #a3a3a3 \
        -font {-family {@MS Gothic} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #800000 -text {Input your Choise:} 
    vTcl:DefineAlias "$site_3_0.lab49" "Label2" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #008000 -disabledforeground #a3a3a3 \
        -font {-family @Meiryo -size 10 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Send 
    vTcl:DefineAlias "$site_3_0.but50" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ff0000 -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Yes 
    vTcl:DefineAlias "$site_3_0.but51" "Button3" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but52 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ff0000 -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text No 
    vTcl:DefineAlias "$site_3_0.but52" "Button4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab53 \
        -background #ff8080 -disabledforeground #a3a3a3 \
        -font {-family {MS PGothic} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ff0000 -text {Do You Want To Continue?} 
    vTcl:DefineAlias "$site_3_0.lab53" "Label3" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab45 \
        -in $site_3_0 -x 0 -y 0 -width 0 -relwidth 0.998 -height 0 \
        -relheight 0.16 -anchor nw -bordermode ignore 
    place $site_3_0.but46 \
        -in $site_3_0 -x 0 -relx 0.37 -y 0 -rely 0.157 -width 137 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lis47 \
        -in $site_3_0 -x 0 -relx 0.168 -y 0 -rely 0.27 -width 0 \
        -relwidth 0.713 -height 0 -relheight 0.274 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex48 \
        -in $site_3_0 -x 0 -relx 0.487 -y 0 -rely 0.607 -width 0 \
        -relwidth 0.242 -height 0 -relheight 0.099 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.101 -y 0 -rely 0.607 -width 0 \
        -relwidth 0.376 -height 0 -relheight 0.092 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 0 -relx 0.739 -y 0 -rely 0.607 -width 87 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but51 \
        -in $site_3_0 -x 0 -relx 0.269 -y 0 -rely 0.876 -width 107 \
        -relwidth 0 -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but52 \
        -in $site_3_0 -x 0 -relx 0.622 -y 0 -rely 0.876 -width 97 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.168 -y 0 -rely 0.742 -width 0 \
        -relwidth 0.696 -height 0 -relheight 0.092 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra44 \
        -in $top -x 0 -y 0 -width 0 -relwidth 0.992 -height 0 \
        -relheight 0.989 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

