#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.3
#  in conjunction with Tcl version 8.6
#    Jul 27, 2020 10:45:56 AM IST  platform: Windows NT

import sys
import random

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import smile_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    smile_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    smile_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def start(self):
        self.Listbox1.insert(tk.END,"--------Rules of the game----------" )
        self.Listbox1.insert(tk.END, "1.Rock vs paper --->paper wins")
        self.Listbox1.insert(tk.END, "2.Rock vs scissor--->rock wins")
        self.Listbox1.insert(tk.END, "3.paper vs scissor---> scissor wins")
        self.Listbox1.insert(tk.END, "Input Your Choise Below")
    def take(self):
        ch = self.Text1.get("1.0")
        ch = int(ch)
        while ch > 3 or ch < 1:
            ch = int(input("enter your valied input here:"))
        if ch == 1:
            choicename = "rock"
        elif ch == 2:
            choicename = "paper"
        else:
            choicename = "scissor"
        self.Listbox1.insert(tk.END, "Your choice is:"+choicename)
        self.Listbox1.insert(tk.END, "Now it's Bell's Chance")
        compchoice = random.randint(1, 3)
        if compchoice == 1:
            compchoicename = "rock"
        elif compchoice == 2:
            compchoicename = "paper"
        else:
            compchoicename = "scissor"

        self.Listbox1.insert(tk.END, "so Bell's choice is:"+compchoicename)
        self.Listbox1.insert(tk.END, "--------------------" )
        self.Listbox1.insert(tk.END, choicename + " " + "vs" +" "+ compchoicename)

        if ((ch == 1 and compchoice == 2) or (ch == 2 and compchoice == 1)):
            self.Listbox1.insert(tk.END, "paper wins --->>>")
            finalresult = " paper"
        elif ((ch == 1 and compchoice == 3) or (ch == 3 and compchoice == 1)):
            self.Listbox1.insert(tk.END,"rock wins --->>>" )
            finalresult = " rock"
        else:
            self.Listbox1.insert(tk.END,"sicssor wins --->>>" )
            finalresult = "sicssor"
        if finalresult == choicename:
            self.Listbox1.insert(tk.END,"-----you are the winner-----" )

        else:
            self.Listbox1.insert(tk.END, "-----computer wins------")
            self.Listbox1.insert(tk.END, "do you want play again yes or no")



    def no(self):
        self.Listbox1.insert(tk.END, "Thanks for sharing your valuble time with us")
        

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Century} -size 12"
        font12 = "-family {@Meiryo} -size 10"
        font13 = "-family {MS PGothic} -size 12 -weight bold"
        font16 = "-family {@MS Gothic} -size 12 -weight bold"
        font9 = "-family {@Meiryo} -size 18 -weight bold"

        top.geometry("600x450+377+148")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.0, rely=0.0, relheight=0.989, relwidth=0.992)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#ff8080")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.0, rely=0.0, height=71, width=594)
        self.Label1.configure(background="#ff8080")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#f5010a")
        self.Label1.configure(text='''!!!Let's play Rock,Paper,Scissor!!!''')

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.37, rely=0.157, height=34, width=137)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#008000")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font10)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(command=self.start,text='''Start''')

        self.Listbox1 = tk.Listbox(self.Frame1)
        self.Listbox1.place(relx=0.168, rely=0.27, relheight=0.274
                , relwidth=0.713)
        self.Listbox1.configure(background="#ff8040")
        self.Listbox1.configure(disabledforeground="#a3a3a3")
        self.Listbox1.configure(font="TkFixedFont")
        self.Listbox1.configure(foreground="#000000")

        self.Text1 = tk.Text(self.Frame1)
        self.Text1.place(relx=0.487, rely=0.607, relheight=0.099, relwidth=0.242)

        self.Text1.configure(background="#80ff80")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="#d9d9d9")
        self.Text1.configure(highlightcolor="black")
        self.Text1.configure(insertbackground="black")
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(selectforeground="black")
        self.Text1.configure(wrap="word")

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.101, rely=0.607, height=41, width=224)
        self.Label2.configure(background="#ff8080")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font16)
        self.Label2.configure(foreground="#800000")
        self.Label2.configure(text='''Input your Choise:''')

        self.Button2 = tk.Button(self.Frame1)
        self.Button2.place(relx=0.739, rely=0.607, height=44, width=87)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#008000")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font=font12)
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(command=self.take,text='''Send''')

        self.Button3 = tk.Button(self.Frame1)
        self.Button3.place(relx=0.269, rely=0.876, height=34, width=107)
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#ff0000")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Yes''')

        self.Button4 = tk.Button(self.Frame1)
        self.Button4.place(relx=0.622, rely=0.876, height=34, width=97)
        self.Button4.configure(activebackground="#ececec")
        self.Button4.configure(activeforeground="#000000")
        self.Button4.configure(background="#ff0000")
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")
        self.Button4.configure(command=self.no,text='''No''')

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.168, rely=0.742, height=41, width=414)
        self.Label3.configure(background="#ff8080")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font13)
        self.Label3.configure(foreground="#ff0000")
        self.Label3.configure(text='''Do You Want To Continue?''')

if __name__ == '__main__':
    vp_start_gui()





